#! /bin/bash

export DISPLAY_NUMBER=$(echo $DISPLAY | cut -d. -f1 | cut -d: -f2)

docker run \
   `# X11 sharing`                           \
   -v /tmp/:/tmp/                            \
   -e DISPLAY=:${DISPLAY_NUMBER}             \
   --device=/dev/dri:/dev/dri                \
   --device=/dev/snd:/dev/snd                \
                                             \
   `# maya-environment (thanks mottoso!!)`   \
   -e MAYA_DISABLE_CIP=1                     \
   --user ricou                              \
   --workdir /home/ricou/                    \
   --rm                                      \
   --name maya_run                           \
   -ti maya
